# permissions for end users to view mesos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mesos-viewer-role
rules:
- apiGroups:
  - my.domain
  resources:
  - mesos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my.domain
  resources:
  - mesos/status
  verbs:
  - get
